[project]
name = "secuestro"
version = "0.0.1"
description = "Exploración de la base de secuestros en Antioquia, Cundinamarca y la Guajira"
authors = [
    {name = "Sebasan1709",email = "sbstnangel@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas (>=2.3.0,<3.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "numpy (>=2.2.6,<3.0.0)",
    "scikit-learn (>=1.7.0,<2.0.0)",
    "ipywidgets (>=8.1.7,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
